### ISSUE TITLE
Removing throwing inserters quickly after placing them causes crash

### ISSUE THREAD

**Issue by overloader7** [Kiplacon/Renai-Transportation#27]
Sometimes it does, sometimes it doesn't. I also have bob's inserters, and it feels as if changing a setting (doesn't matter if its a same inserter or not) increases reproduceability. Doesn't happen outside of factorissimo buildings. The overflow prevention2 setting is on. Disabling it seems to stop the crashes.
"
Error while running event RenaiTransportation::on_script_trigger_effect (ID 152)
__RenaiTransportation__/script/event/effect_triggered.lua:247:
attempt to index field 'source_entity' (a nil value)
stack traceback:
__RenaiTransportation__/script/event/effect_triggered.lua:247: in function
<__RenaiTransportation__/script/event/effect_triggered.lua:30>
"
There is also a variant with error on line 200

Speaking of bob's inserters, if the angle is within throwable, it throws instantly, no matter the insrter speed. Is it possible to add some sort of flat delay for all throws?

**Comment by overloader7** [comment]
Also deconstructing them with [nanites](https://mods.factorio.com/mod/Nanobots) doesn't seem to create the error

**Comment by overloader7** [comment]
Same error happens when putting two directed bouncers in a loop, then throwing a lot(multiple hundreds) of items on them, then removing one (anywhere in the world). Can't get it to crash by simply removing a bouncer.

**Comment by overloader7** [comment]
If I understand correctly, 'MaybeIllBeTracer-RT' is used to check the path that thrown items will take to make overflow prevention account for items in flight? And sometimes somehow when the tracing projectile finishes, it doesn't find the thrower that it was launched from? 

In this case, is it possible to make the tracing projectile's speed infinite? Or make a check if its a tracer&thrower is nil, and then abort the whole function and return?

Also the overflow prevention seems bit wonky when throwing onto wagon with a hatch, which I thought is needed for getting items in wagon :))

**Comment by overloader7** [comment]
Actually, quickly placing and removing them outside of factorissimo building works too, but inside it works even with some delay

**Comment by Kiplacon** [comment]
Hey, sorry for the late reply I dont check github much. Like what you were thinking, I do use the Tracer projectile to find what a thrower is pointing to and log the target to help prevent overflow. The problem is that I make sure only 1 tracking projectile is launched at a time for each thrower so when the tracker lands, I set it so that the thrower it came from can start another tracker, but if the thrower was removed, it can't find it and that apparently causes the crash. I was able to recreate it best with the two back and forth bounce pad method. To fix it I added a couple extra checks at both those lines for missing throwers and so far (5 minutes of testing) I haven't had the crash happen again. You can try it out in 0.8.9 I'll upload soon
