### ISSUE TITLE
Non-recoverable error (crash)

### ISSUE THREAD

**Issue by GetTuh** [Kiplacon/Renai-Transportation#29]
Debug in the screenshot. Only mods installed : Renai Transportation & Helmod

![factorio_snysumut1t](https://user-images.githubusercontent.com/27581581/148689075-a6844205-4777-4194-8e46-251bf4a8277f.png)

**Comment by Kiplacon** [comment]
That's a weird spot for an error to happen, two quick questions: 
1. is this on a new or existing world
2. Roughly when did this happen (after placing/breaking/replacing something, randomly, etc.)

**Comment by GetTuh** [comment]
I couldn't recreate this particular crash and it didn't happen again, but another one kept popping up consistently:

Just recreate the things I did in this GIF. I think throwing at a cliff made it break.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/27581581/148837611-731ce987-f938-41d1-b0a3-7727a0365858.gif)

Save file : [crash.zip](https://github.com/Kiplacon/Renai-Transportation/files/7841794/crash.zip)

**Comment by Kiplacon** [comment]
I'm not certain about the first crash but I was able to fix the issue with the cliffs, it happened because cliffs don't use the same ID system as most things we can place in game. Hopefully it shouldnt crash anymore on 0.9.4

By the way I don't know if you did it just for the clip, but if you unlocked the ability to adjust thrower range, you can adjust range before placing it with the adjust key while holding it.

**Comment by GetTuh** [comment]
Thanks! 
No I didn't know about adjusting the range before placing. Thanks for the tip!
